# -*- coding: utf-8 -*-
"""app2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kfa2JVyk9LHmpCO45dEjaL0zgQCxfJ6q
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# Title of the app
st.title('Interactive Crime Statistics Visualization App')

# Pre-loaded dataset for crime statistics
data = {
    'Crime Type': ['Theft', 'Assault', 'Burglary', 'Vandalism', 'Drug Offenses'],
    'Incidents': [150, 80, 120, 60, 90],
    'Reported Cases': [50, 30, 40, 20, 25]
}
df = pd.DataFrame(data)

# Display the dataset
st.write("Crime Statistics Data:")
st.write(df)

# Let the user select columns for the chart
columns = df.columns.tolist()

# Dropdowns for X and Y axes selection
x_axis = st.selectbox('Select column for X-axis', columns)
y_axis = st.selectbox('Select column for Y-axis', columns)

# Choose chart type: Bar Chart or Line Chart
chart_type = st.selectbox('Select chart type', ['Bar Chart', 'Line Chart'])

# Display chart based on user selections
if chart_type == 'Bar Chart':
    st.bar_chart(df[[x_axis, y_axis]].set_index(x_axis))
elif chart_type == 'Line Chart':
    st.line_chart(df[[x_axis, y_axis]].set_index(x_axis))

# Include a graphic of the University of New Mexico
st.subheader('University of New Mexico')
# You can replace the path below with the path to the graphic you want to use
image_path = 'https://github.com/gdean7/my_first_repo/blob/main/University_of_New_Mexico_Main_Campus.jpg'
img = mpimg.imread(image_path)
st.image(img, caption='University of New Mexico', use_column_width=True)
